# Generated by Django 5.0.6 on 2024-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_accessories', '0002_alter_partyaccessory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyaccessory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
