# Generated by Django 5.0.6 on 2024-06-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_accessories', '0003_alter_partyaccessory_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartyAccessoryReview',
        ),
    ]
