# Generated by Django 5.0.6 on 2024-06-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
