# Generated by Django 5.0.6 on 2024-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_cake_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
