# Generated by Django 5.0.6 on 2024-06-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_cake_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CakeReview',
        ),
    ]
