# Generated by Django 5.0.6 on 2024-07-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_delete_cakereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flavour_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_cakes', to='cakes.trendingtype')),
                ('trend_score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='cakes.cake')),
            ],
            options={
                'ordering': ['-trend_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='flavours',
            field=models.ManyToManyField(blank=True, related_name='cakes', to='cakes.flavour'),
        ),
    ]
