# Generated by Django 5.0.4 on 2024-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_flavour_cake_flavours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
