# Generated by Django 5.0.6 on 2024-06-29 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_delete_cakereview'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CakeReview',
            new_name='Review',
        ),
    ]
