# Generated by Django 5.0.6 on 2024-08-11 10:48

import django.db.models.deletion
from django.db import migrations, models


def set_default_size(apps, schema_editor):
    CakeSize = apps.get_model('cakes', 'CakeSize')
    default_size = CakeSize.objects.get(id=1)  # Use an existing size ID as default

    CartItem = apps.get_model('orders', 'CartItem')
    CartItem.objects.filter(size__isnull=True).update(size=default_size)

class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.cakesize'),
        ),
    ]
