# Generated by Django 5.0.6 on 2024-08-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='qr_images/')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipt/'),
        ),
    ]
