# Generated by Django 5.0.6 on 2024-06-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='cake_type',
        ),
        migrations.RemoveField(
            model_name='cakesize',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='cakeimage',
            name='cake',
        ),
        migrations.DeleteModel(
            name='CakeType',
        ),
        migrations.DeleteModel(
            name='CakeSize',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='CakeImage',
        ),
    ]
